# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - python-testt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6ff7a8a4a18e478c9916479c619e8789 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_be0854ce8df8461a91c7c93d9b0f9af3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6ff7a8a4a18e478c9916479c619e8789 }}/s6suraj/python:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'python-testt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0de851749f5a4da8b150ddf0f47fd356 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6ff7a8a4a18e478c9916479c619e8789 }}/s6suraj/python:${{ github.sha }}'